// Generated by gencpp from file ros_its_msgs/CAM_simplified.msg
// DO NOT EDIT!


#ifndef ROS_ITS_MSGS_MESSAGE_CAM_SIMPLIFIED_H
#define ROS_ITS_MSGS_MESSAGE_CAM_SIMPLIFIED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_its_msgs
{
template <class ContainerAllocator>
struct CAM_simplified_
{
  typedef CAM_simplified_<ContainerAllocator> Type;

  CAM_simplified_()
    : car_name()
    , latitude(0.0)
    , longitude(0.0)
    , altitude_altitudeValue(0.0)
    , heading_headingValue(0.0)
    , speed_speedValue(0.0)
    , driveDirection(0)
    , steeringWheelAngle_steeringWheelAngleValue(0.0)
    , gasPedalPercent_Value(0.0)
    , brakePedalPercent_Value(0.0)  {
    }
  CAM_simplified_(const ContainerAllocator& _alloc)
    : car_name(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , altitude_altitudeValue(0.0)
    , heading_headingValue(0.0)
    , speed_speedValue(0.0)
    , driveDirection(0)
    , steeringWheelAngle_steeringWheelAngleValue(0.0)
    , gasPedalPercent_Value(0.0)
    , brakePedalPercent_Value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _car_name_type;
  _car_name_type car_name;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef float _altitude_altitudeValue_type;
  _altitude_altitudeValue_type altitude_altitudeValue;

   typedef float _heading_headingValue_type;
  _heading_headingValue_type heading_headingValue;

   typedef float _speed_speedValue_type;
  _speed_speedValue_type speed_speedValue;

   typedef int8_t _driveDirection_type;
  _driveDirection_type driveDirection;

   typedef float _steeringWheelAngle_steeringWheelAngleValue_type;
  _steeringWheelAngle_steeringWheelAngleValue_type steeringWheelAngle_steeringWheelAngleValue;

   typedef float _gasPedalPercent_Value_type;
  _gasPedalPercent_Value_type gasPedalPercent_Value;

   typedef float _brakePedalPercent_Value_type;
  _brakePedalPercent_Value_type brakePedalPercent_Value;





  typedef boost::shared_ptr< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> const> ConstPtr;

}; // struct CAM_simplified_

typedef ::ros_its_msgs::CAM_simplified_<std::allocator<void> > CAM_simplified;

typedef boost::shared_ptr< ::ros_its_msgs::CAM_simplified > CAM_simplifiedPtr;
typedef boost::shared_ptr< ::ros_its_msgs::CAM_simplified const> CAM_simplifiedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_its_msgs::CAM_simplified_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_its_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ros_its_msgs': ['/home/ps/CISTER/ENABLE_S3/ENABLE_S3_Code/CISTER_runtime_verification/src/ros_its_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9432af28627cff95b2a09a36b5176ec0";
  }

  static const char* value(const ::ros_its_msgs::CAM_simplified_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9432af28627cff95ULL;
  static const uint64_t static_value2 = 0xb2a09a36b5176ec0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_its_msgs/CAM_simplified";
  }

  static const char* value(const ::ros_its_msgs::CAM_simplified_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDs\n\
\n\
string car_name\n\
\n\
# Reference Position\n\
#int32 latitude\n\
#int64 longitude\n\
#int32 altitude_altitudeValue\n\
\n\
float32 latitude\n\
float64 longitude\n\
float32 altitude_altitudeValue\n\
\n\
# BasicVehicleContainerHighFrequency (Simplified)\n\
\n\
#uint16 heading_headingValue\n\
#uint16 speed_speedValue\n\
float32 heading_headingValue\n\
float32 speed_speedValue\n\
\n\
int8 driveDirection\n\
\n\
#int16 steeringWheelAngle_steeringWheelAngleValue\n\
float32 steeringWheelAngle_steeringWheelAngleValue\n\
\n\
float32 gasPedalPercent_Value\n\
float32 brakePedalPercent_Value\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::ros_its_msgs::CAM_simplified_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.car_name);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude_altitudeValue);
      stream.next(m.heading_headingValue);
      stream.next(m.speed_speedValue);
      stream.next(m.driveDirection);
      stream.next(m.steeringWheelAngle_steeringWheelAngleValue);
      stream.next(m.gasPedalPercent_Value);
      stream.next(m.brakePedalPercent_Value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CAM_simplified_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_its_msgs::CAM_simplified_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_its_msgs::CAM_simplified_<ContainerAllocator>& v)
  {
    s << indent << "car_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.car_name);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude_altitudeValue: ";
    Printer<float>::stream(s, indent + "  ", v.altitude_altitudeValue);
    s << indent << "heading_headingValue: ";
    Printer<float>::stream(s, indent + "  ", v.heading_headingValue);
    s << indent << "speed_speedValue: ";
    Printer<float>::stream(s, indent + "  ", v.speed_speedValue);
    s << indent << "driveDirection: ";
    Printer<int8_t>::stream(s, indent + "  ", v.driveDirection);
    s << indent << "steeringWheelAngle_steeringWheelAngleValue: ";
    Printer<float>::stream(s, indent + "  ", v.steeringWheelAngle_steeringWheelAngleValue);
    s << indent << "gasPedalPercent_Value: ";
    Printer<float>::stream(s, indent + "  ", v.gasPedalPercent_Value);
    s << indent << "brakePedalPercent_Value: ";
    Printer<float>::stream(s, indent + "  ", v.brakePedalPercent_Value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ITS_MSGS_MESSAGE_CAM_SIMPLIFIED_H
